# Generated by Django 4.1.3 on 2022-11-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.TextField(default='', max_length=1200),
        ),
    ]
